### ISSUE TITLE
UDP is not fully stateless

### ISSUE THREAD

**Issue by bortzmeyer** [BRE-ISNIC/bre-doh-analysis#2]
"stateless UDP" Be careful, UDP cannot be completely stateless since you have to remember the path MTU to the target (specially for IPv6). On FreeBSD at least, implementation of UDP uses state.

**Comment by BRE-ISNIC** [comment]
UDP itself is stateless.

The fact that some implementations may add state as an optimization or to facilitate the more common use-cases doesn't really change that. And it certainly doesn't change the overall analysis, which is that TCP requires both more resources and more round-trips to communicate.
