### ISSUE TITLE
Small number of DoH resolvers

### ISSUE THREAD

**Issue by bortzmeyer** [BRE-ISNIC/bre-doh-analysis#6]
"Instead, that capability is shifted to a relatively smaller number of dedicated DoH providers" This is not a property of DoH. Current public resolvers have the same issue. The solution is to have many DoH resolvers (the protocol does not force you to use Cloudflare).

**Comment by BRE-ISNIC** [comment]
This is in the politics section. I'm not talking about how the protocol works here.
